pesos = int(input("What do you have left in pesos? "))
soles = int(input("What do you have left in soles? "))
reais = int(input("What do you have left in reais? "))
USD = (pesos / 4000) + (soles / 3.5714) + (reais / 5.5555)
print(USD)